### PR TITLE
Update environment.yml

### PR DESCRIPTION
**Pull request by erogluorhan**
Update environment.yml to:
- Revert installation of `uxarray` from the main branch to conda relases
- Remove `jupyter_server` per [this](https://github.com/ProjectPythia/cookbook-template/pull/166)

### CODE REVIEW

**Comment by erogluorhan** [comment]
Hey @philipc2 you may want to see the error in the book build process as it maybe related to April's release

**Comment by philipc2** [comment]
Previously, we were raising a warning when the user attending to do `uxds.plot()`, however now we are raising an exception with a more detailed 

## Before

image

## After

image

I wonder what the correct way to show off an exception is in a notebook without it breaking the build?

**Comment by erogluorhan** [comment]
> Previously, we were raising a warning when the user attending to do `uxds.plot()`, however now we are raising an exception with a more detailed
> 
> ## Before
> image
> 
> ## After
> image
> 
> I wonder what the correct way to show off an exception is in a notebook without it breaking the build?

Got it! 

I don't know if there is a correct one among multiple ways to do this. One immediate way would be to put a try-catch block into that cell (don't know if it would look elegant though), and print something out of the cell in the catch to show there was an exception.

**Comment by philipc2** [comment]
> > Previously, we were raising a warning when the user attending to do `uxds.plot()`, however now we are raising an exception with a more detailed
> > ## Before
> > image
> > ## After
> > image
> > I wonder what the correct way to show off an exception is in a notebook without it breaking the build?
> 
> Got it!
> 
> I don't know if there is a correct one among multiple ways to do this. One immediate way would be to put a try-catch block into that cell (don't know if it would look elegant though), and print something out of the cell in the catch to show there was an exception.

Yeah, I thought of the try-catch, but from a readers perspective it might be confusing. 

Maybe we don't need to run `uxds.plot()` and we could just document it in the markdown?

**Comment by erogluorhan** [comment]
> Yeah, I thought of the try-catch, but from a readers perspective it might be confusing.
> 
> Maybe we don't need to run `uxds.plot()` and we could just document it in the markdown?

How about commenting that out and putting a comment before it to say running that line would show the exception? If this makes sense, I can add it to this PR

**Comment by philipc2** [comment]
> > Yeah, I thought of the try-catch, but from a readers perspective it might be confusing.
> > Maybe we don't need to run `uxds.plot()` and we could just document it in the markdown?
> 
> How about commenting that out and putting a comment before it to say running that line would show the exception? If this makes sense, I can add it to this PR

That sounds like a great idea, go ahead and include it in this PR!

**Comment by erogluorhan** [comment]
> > > Yeah, I thought of the try-catch, but from a readers perspective it might be confusing.
> > > Maybe we don't need to run `uxds.plot()` and we could just document it in the markdown?
> > 
> > 
> > How about commenting that out and putting a comment before it to say running that line would show the exception? If this makes sense, I can add it to this PR
> 
> That sounds like a great idea, go ahead and include it in this PR!

Done! Feel free to give it a review now that we got the build fixed

**Review by philipc2 — APPROVED** [review]
All looks good!

**Pull request merged**
